# Generated by Django 5.2.4 on 2025-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0018_delete_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalknownplayer',
            name='creator_code',
            field=models.CharField(blank=True, help_text='Creator/supporter code to promote in shop', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='knownplayer',
            name='creator_code',
            field=models.CharField(blank=True, help_text='Creator/supporter code to promote in shop', max_length=50, null=True),
        ),
    ]
