# Generated by Django 5.2.4 on 2025-09-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0020_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsusperson",
            name="api_ban",
            field=models.BooleanField(default=False, help_text="Was the ban set by the API?"),
        ),
        migrations.AddField(
            model_name="historicalsusperson",
            name="api_sus",
            field=models.BooleanField(default=False, help_text="Was the sus flag set by the API?"),
        ),
        migrations.AddField(
            model_name="susperson",
            name="api_ban",
            field=models.BooleanField(default=False, help_text="Was the ban set by the API?"),
        ),
        migrations.AddField(
            model_name="susperson",
            name="api_sus",
            field=models.BooleanField(default=False, help_text="Was the sus flag set by the API?"),
        ),
    ]
