# Generated by Django 5.2.4 on 2025-09-20 18:05

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0022_add_moderation_record_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationrecord',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='moderationrecord',
            name='sus_moderat_tower_i_a6ef91_idx',
        ),
        migrations.RemoveIndex(
            model_name='moderationrecord',
            name='sus_moderat_tower_i_853806_idx',
        ),
        migrations.RemoveIndex(
            model_name='moderationrecord',
            name='sus_moderat_known_p_ef5eeb_idx',
        ),
        migrations.RemoveField(
            model_name='historicalmoderationrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='moderationrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalmoderationrecord',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this moderation action began'),
        ),
        migrations.AddField(
            model_name='moderationrecord',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this moderation action began'),
        ),
        migrations.AddIndex(
            model_name='moderationrecord',
            index=models.Index(fields=['tower_id', 'resolved_at'], name='sus_moderat_tower_i_8e7ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationrecord',
            index=models.Index(fields=['tower_id', 'moderation_type', 'resolved_at'], name='sus_moderat_tower_i_fc534f_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationrecord',
            index=models.Index(fields=['known_player', 'resolved_at'], name='sus_moderat_known_p_d2ccc2_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationrecord',
            index=models.Index(fields=['started_at'], name='sus_moderat_started_40a2b5_idx'),
        ),
    ]
