# Generated by Django 5.2.4 on 2025-09-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0023_convert_moderation_to_datetime_based"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmoderationrecord",
            name="resolution_note",
        ),
        migrations.RemoveField(
            model_name="moderationrecord",
            name="resolution_note",
        ),
    ]
