# Generated by Django 5.2.4 on 2025-11-07 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0024_remove_resolution_note_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmoderationrecord",
            name="needs_zendesk_ticket",
            field=models.BooleanField(default=False, help_text="Moderation record needs a Zendesk ticket created"),
        ),
        migrations.AddField(
            model_name="historicalmoderationrecord",
            name="zendesk_last_attempt",
            field=models.DateTimeField(blank=True, help_text="When Zendesk ticket creation was last attempted", null=True),
        ),
        migrations.AddField(
            model_name="historicalmoderationrecord",
            name="zendesk_retry_count",
            field=models.SmallIntegerField(default=0, help_text="Number of failed Zendesk ticket creation attempts"),
        ),
        migrations.AddField(
            model_name="historicalmoderationrecord",
            name="zendesk_ticket_id",
            field=models.IntegerField(blank=True, help_text="Zendesk ticket ID once created", null=True),
        ),
        migrations.AddField(
            model_name="moderationrecord",
            name="needs_zendesk_ticket",
            field=models.BooleanField(default=False, help_text="Moderation record needs a Zendesk ticket created"),
        ),
        migrations.AddField(
            model_name="moderationrecord",
            name="zendesk_last_attempt",
            field=models.DateTimeField(blank=True, help_text="When Zendesk ticket creation was last attempted", null=True),
        ),
        migrations.AddField(
            model_name="moderationrecord",
            name="zendesk_retry_count",
            field=models.SmallIntegerField(default=0, help_text="Number of failed Zendesk ticket creation attempts"),
        ),
        migrations.AddField(
            model_name="moderationrecord",
            name="zendesk_ticket_id",
            field=models.IntegerField(blank=True, help_text="Zendesk ticket ID once created", null=True),
        ),
        migrations.AddIndex(
            model_name="moderationrecord",
            index=models.Index(fields=["needs_zendesk_ticket", "zendesk_retry_count", "created_at"], name="idx_zendesk_queue"),
        ),
        migrations.AddIndex(
            model_name="moderationrecord",
            index=models.Index(fields=["needs_zendesk_ticket"], name="idx_needs_zendesk"),
        ),
    ]
