# Generated by Django 5.2.4 on 2025-11-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0025_add_zendesk_queue_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmoderationrecord",
            name="needs_zendesk_ticket",
            field=models.BooleanField(
                default=True,
                help_text="Moderation record needs a Zendesk ticket created"
            ),
        ),
        migrations.AlterField(
            model_name="moderationrecord",
            name="needs_zendesk_ticket",
            field=models.BooleanField(
                default=True,
                help_text="Moderation record needs a Zendesk ticket created"
            ),
        ),
    ]
