# Generated by Django 5.2.4 on 2025-11-21 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0026_set_zendesk_default_true"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalknownplayer",
            name="django_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Linked Django user account",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knownplayer",
            name="django_user",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked Django user account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="known_player",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
