# Generated by Django 5.2.4 on 2026-01-29 17:57

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0027_historicalknownplayer_django_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Friendly name for this instance (e.g., 'Instance 1', 'Instance 2')", max_length=50, null=True
                    ),
                ),
                ("primary", models.BooleanField(default=False, help_text="Primary instance - determines Discord roles for all linked accounts")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalGameInstance",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Friendly name for this instance (e.g., 'Instance 1', 'Instance 2')", max_length=50, null=True
                    ),
                ),
                ("primary", models.BooleanField(default=False, help_text="Primary instance - determines Discord roles for all linked accounts")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
            ],
            options={
                "verbose_name": "historical game instance",
                "verbose_name_plural": "historical game instances",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLinkedAccount",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[("discord", "Discord"), ("reddit", "Reddit"), ("twitter", "Twitter"), ("twitch", "Twitch")],
                        help_text="Social media platform",
                        max_length=20,
                    ),
                ),
                ("account_id", models.CharField(help_text="Platform-specific account ID or username", max_length=100)),
                ("display_name", models.CharField(blank=True, help_text="Display name on this platform (optional)", max_length=100, null=True)),
                ("verified", models.BooleanField(default=False, help_text="Has this account link been verified?")),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text="When this account was verified", null=True),
                ),
                (
                    "primary",
                    models.BooleanField(default=False, help_text="Is this the primary account for this platform? (only one per player per platform)"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
            ],
            options={
                "verbose_name": "historical linked account",
                "verbose_name_plural": "historical linked accounts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LinkedAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[("discord", "Discord"), ("reddit", "Reddit"), ("twitter", "Twitter"), ("twitch", "Twitch")],
                        help_text="Social media platform",
                        max_length=20,
                    ),
                ),
                ("account_id", models.CharField(help_text="Platform-specific account ID or username", max_length=100)),
                ("display_name", models.CharField(blank=True, help_text="Display name on this platform (optional)", max_length=100, null=True)),
                ("verified", models.BooleanField(default=False, help_text="Has this account link been verified?")),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text="When this account was verified", null=True),
                ),
                (
                    "primary",
                    models.BooleanField(default=False, help_text="Is this the primary account for this platform? (only one per player per platform)"),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="moderationrecord",
            name="sus_moderat_known_p_d2ccc2_idx",
        ),
        migrations.RemoveField(
            model_name="historicalmoderationrecord",
            name="known_player",
        ),
        migrations.RemoveField(
            model_name="moderationrecord",
            name="known_player",
        ),
        migrations.AlterField(
            model_name="historicalknownplayer",
            name="discord_id",
            field=models.CharField(blank=True, help_text="DEPRECATED: Discord numeric id (use linked_accounts instead)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmoderationrecord",
            name="tower_id",
            field=models.CharField(
                db_index=True, help_text="Tower ID that triggered moderation (always stored regardless of verification status)", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="historicalplayerid",
            name="player",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="DEPRECATED: Direct link to player (use game_instance.player)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sus.knownplayer",
            ),
        ),
        migrations.AlterField(
            model_name="historicalplayerid",
            name="primary",
            field=models.BooleanField(default=False, help_text="Primary ID for this game instance (in case of ID changes)"),
        ),
        migrations.AlterField(
            model_name="knownplayer",
            name="discord_id",
            field=models.CharField(blank=True, help_text="DEPRECATED: Discord numeric id (use linked_accounts instead)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="moderationrecord",
            name="tower_id",
            field=models.CharField(
                db_index=True, help_text="Tower ID that triggered moderation (always stored regardless of verification status)", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="playerid",
            name="player",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Direct link to player (use game_instance.player)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ids",
                to="sus.knownplayer",
            ),
        ),
        migrations.AlterField(
            model_name="playerid",
            name="primary",
            field=models.BooleanField(default=False, help_text="Primary ID for this game instance (in case of ID changes)"),
        ),
        migrations.AddField(
            model_name="gameinstance",
            name="player",
            field=models.ForeignKey(
                help_text="The player who owns this game instance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_instances",
                to="sus.knownplayer",
            ),
        ),
        migrations.AddField(
            model_name="historicalmoderationrecord",
            name="game_instance",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="GameInstance being moderated (null for unverified players)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sus.gameinstance",
            ),
        ),
        migrations.AddField(
            model_name="historicalplayerid",
            name="game_instance",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The game instance this Tower ID belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sus.gameinstance",
            ),
        ),
        migrations.AddField(
            model_name="moderationrecord",
            name="game_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="GameInstance being moderated (null for unverified players)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_records",
                to="sus.gameinstance",
            ),
        ),
        migrations.AddField(
            model_name="playerid",
            name="game_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="The game instance this Tower ID belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_ids",
                to="sus.gameinstance",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationrecord",
            index=models.Index(fields=["game_instance", "resolved_at"], name="sus_moderat_game_in_b2723f_idx"),
        ),
        migrations.AddIndex(
            model_name="moderationrecord",
            index=models.Index(fields=["game_instance", "moderation_type", "resolved_at"], name="sus_moderat_game_in_7071a6_idx"),
        ),
        migrations.AddField(
            model_name="historicalgameinstance",
            name="history_user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="historicalgameinstance",
            name="player",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The player who owns this game instance",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sus.knownplayer",
            ),
        ),
        migrations.AddField(
            model_name="historicallinkedaccount",
            name="history_user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="historicallinkedaccount",
            name="player",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The player this account belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sus.knownplayer",
            ),
        ),
        migrations.AddField(
            model_name="historicallinkedaccount",
            name="role_source_instance",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Which game instance provides Discord roles for this account. Null = no roles assigned.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sus.gameinstance",
            ),
        ),
        migrations.AddField(
            model_name="linkedaccount",
            name="player",
            field=models.ForeignKey(
                help_text="The player this account belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_accounts",
                to="sus.knownplayer",
            ),
        ),
        migrations.AddField(
            model_name="linkedaccount",
            name="role_source_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Which game instance provides Discord roles for this account. Null = no roles assigned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_accounts_receiving_roles",
                to="sus.gameinstance",
            ),
        ),
        migrations.AddIndex(
            model_name="linkedaccount",
            index=models.Index(fields=["platform", "account_id"], name="sus_linkeda_platfor_f381aa_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="linkedaccount",
            unique_together={("platform", "account_id")},
        ),
    ]
