# Generated by Django 5.2.4 on 2026-01-22 17:20

import datetime

from django.db import migrations
from django.utils import timezone


def migrate_to_game_instance_model(apps, schema_editor):
    """
    Migrate existing data to the new game-instance-centric model:
    1. Create LinkedAccount for each KnownPlayer with discord_id
    2. Create a single "Instance 1" GameInstance for each KnownPlayer (marked as primary)
    3. Link all existing PlayerIds to their player's GameInstance
    4. Link all existing ModerationRecords to their tower_id's GameInstance
    """
    KnownPlayer = apps.get_model("sus", "KnownPlayer")
    LinkedAccount = apps.get_model("sus", "LinkedAccount")
    GameInstance = apps.get_model("sus", "GameInstance")
    PlayerId = apps.get_model("sus", "PlayerId")
    ModerationRecord = apps.get_model("sus", "ModerationRecord")

    migrated_players = 0
    migrated_linked_accounts = 0
    migrated_instances = 0
    migrated_player_ids = 0
    migrated_moderation_records = 0

    # Process each KnownPlayer
    for player in KnownPlayer.objects.all():
        # 2. Create single GameInstance for this player (do this BEFORE LinkedAccount so we can reference it)
        game_instance = GameInstance.objects.create(
            player=player,
            name="Instance 1",
            primary=True,  # This is their only instance, so it's primary
        )
        migrated_instances += 1

        # 1. Create LinkedAccount if player has discord_id
        if player.discord_id:
            # Use get_or_create to handle duplicate discord_ids (same Discord account linked to multiple players)
            linked_account, created = LinkedAccount.objects.get_or_create(
                platform="discord",
                account_id=player.discord_id,
                defaults={
                    "player": player,
                    "display_name": player.name or "",
                    "verified": True,
                    "verified_at": timezone.make_aware(datetime.datetime(2020, 1, 1)),  # Historical verification date
                    "primary": True,  # First Discord account is primary
                    "role_source_instance": game_instance,  # Set to their primary/first instance
                },
            )
            if created:
                migrated_linked_accounts += 1
            else:
                # Discord account already linked to another player - this is a data quality issue
                # Keep the first player link, log the duplicate
                print(f"⚠️  Discord ID {player.discord_id} already linked to player {linked_account.player_id}, skipping player {player.id}")

        # 3. Link all PlayerIds for this player to the new GameInstance
        player_ids = PlayerId.objects.filter(player=player)
        for player_id in player_ids:
            player_id.game_instance = game_instance
            player_id.save(update_fields=["game_instance"])
            migrated_player_ids += 1

        migrated_players += 1

    # 4. Link ModerationRecords to GameInstances
    # For each ModerationRecord, find the GameInstance via tower_id → PlayerId → GameInstance
    for mod_record in ModerationRecord.objects.filter(game_instance__isnull=True):
        try:
            player_id = PlayerId.objects.select_related("game_instance").get(id=mod_record.tower_id)
            if player_id.game_instance:
                mod_record.game_instance = player_id.game_instance
                mod_record.save(update_fields=["game_instance"])
                migrated_moderation_records += 1
        except PlayerId.DoesNotExist:
            # Tower ID not in our system yet - leave game_instance as null
            pass

    print("Migration complete:")
    print(f"  - Processed {migrated_players} KnownPlayers")
    print(f"  - Created {migrated_linked_accounts} LinkedAccounts")
    print(f"  - Created {migrated_instances} GameInstances")
    print(f"  - Linked {migrated_player_ids} PlayerIds to GameInstances")
    print(f"  - Linked {migrated_moderation_records} ModerationRecords to GameInstances")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by removing LinkedAccounts and GameInstances.
    PlayerIds and ModerationRecords revert to using the deprecated player FK.
    """
    LinkedAccount = apps.get_model("sus", "LinkedAccount")
    GameInstance = apps.get_model("sus", "GameInstance")
    PlayerId = apps.get_model("sus", "PlayerId")
    ModerationRecord = apps.get_model("sus", "ModerationRecord")

    # Clear game_instance links (they'll fall back to deprecated player FK)
    PlayerId.objects.update(game_instance=None)
    ModerationRecord.objects.update(game_instance=None)

    # Delete all GameInstances and LinkedAccounts
    GameInstance.objects.all().delete()
    LinkedAccount.objects.all().delete()

    print("Reverse migration complete - removed GameInstances and LinkedAccounts")


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0028_gameinstance_historicalgameinstance_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_to_game_instance_model, reverse_migration),
    ]
