# Generated by Django 5.2.4 on 2026-02-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0029_migrate_existing_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallinkedaccount",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is this account link active? Inactive accounts are retired/disabled and hidden from regular users."
            ),
        ),
        migrations.AddField(
            model_name="linkedaccount",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is this account link active? Inactive accounts are retired/disabled and hidden from regular users."
            ),
        ),
    ]
