"""UI components for Battle Conditions cog."""

# Core components
# Administrative interface components
from .admin import (
    ActionMentionableSelect,
    BCPermissionsView,
    BCSettingsView,
    ConfigureGeneratePermButton,
    ConfigureLeaguesButton,
    ConfigureManageSchedulesPermButton,
    ConfigurePermissionsButton,
    ConfigureRunSchedulePermButton,
    ConfigureViewWindowButton,
    CreateScheduleButton,
    DeleteScheduleButton,
    DeleteScheduleSelect,
    EditScheduleButton,
    EditScheduleLeagueSelect,
    EditScheduleSelect,
    LeagueSelect,
    ManageSchedulesButton,
    ScheduleChannelSelect,
    ScheduleManagementView,
    TogglePauseScheduleButton,
    TogglePauseSelect,
)
from .core import (
    ALL_LEAGUES,
    DEFAULT_ENABLED_LEAGUES,
    TOWERBCS_AVAILABLE,
    BattleConditionsCore,
    EditScheduleModal,
    ScheduleTimeModal,
    ViewWindowModal,
)

# Settings integration components
from .settings import (
    BattleConditionsActionMentionableSelect,
    BattleConditionsConfigureGeneratePermButton,
    BattleConditionsConfigureLeaguesButton,
    BattleConditionsConfigureManageSchedulesPermButton,
    BattleConditionsConfigurePermissionsButton,
    BattleConditionsConfigureRunSchedulePermButton,
    BattleConditionsCreateScheduleButton,
    BattleConditionsDeleteScheduleButton,
    BattleConditionsDeleteScheduleSelect,
    BattleConditionsEditScheduleButton,
    BattleConditionsEditScheduleSelect,
    BattleConditionsLeagueSelect,
    BattleConditionsManageSchedulesButton,
    BattleConditionsPermissionsView,
    BattleConditionsScheduleChannelSelect,
    BattleConditionsScheduleManagementView,
    BattleConditionsSettingsView,
    BattleConditionsTogglePauseScheduleButton,
    BattleConditionsTogglePauseSelect,
)

# User interface components
from .user import (
    BCManagementView,
    GenerateBCButton,
    ResendBCButton,
    RunAllSchedulesButton,
    ScheduleLeagueSelect,
    ScheduleSelect,
    SettingsBCButton,
    ViewBCButton,
    ViewLeagueSelect,
)

__all__ = [
    # Core
    "BattleConditionsCore",
    "ScheduleTimeModal",
    "EditScheduleModal",
    "ViewWindowModal",
    "TOWERBCS_AVAILABLE",
    "ALL_LEAGUES",
    "DEFAULT_ENABLED_LEAGUES",
    # User
    "BCManagementView",
    "ViewBCButton",
    "ViewLeagueSelect",
    "GenerateBCButton",
    "ResendBCButton",
    "RunAllSchedulesButton",
    "ScheduleSelect",
    "SettingsBCButton",
    "ScheduleLeagueSelect",
    # Admin
    "BCSettingsView",
    "ConfigureLeaguesButton",
    "LeagueSelect",
    "ConfigurePermissionsButton",
    "ManageSchedulesButton",
    "ScheduleManagementView",
    "CreateScheduleButton",
    "ScheduleChannelSelect",
    "EditScheduleButton",
    "EditScheduleSelect",
    "EditScheduleLeagueSelect",
    "DeleteScheduleButton",
    "DeleteScheduleSelect",
    "TogglePauseScheduleButton",
    "TogglePauseSelect",
    "ConfigureViewWindowButton",
    "BCPermissionsView",
    "ConfigureGeneratePermButton",
    "ConfigureRunSchedulePermButton",
    "ConfigureManageSchedulesPermButton",
    "ActionMentionableSelect",
    # Settings
    "BattleConditionsSettingsView",
    "BattleConditionsConfigureLeaguesButton",
    "BattleConditionsLeagueSelect",
    "BattleConditionsConfigurePermissionsButton",
    "BattleConditionsManageSchedulesButton",
    "BattleConditionsPermissionsView",
    "BattleConditionsConfigureGeneratePermButton",
    "BattleConditionsConfigureRunSchedulePermButton",
    "BattleConditionsConfigureManageSchedulesPermButton",
    "BattleConditionsActionMentionableSelect",
    "BattleConditionsScheduleManagementView",
    "BattleConditionsCreateScheduleButton",
    "BattleConditionsScheduleChannelSelect",
    "BattleConditionsEditScheduleButton",
    "BattleConditionsEditScheduleSelect",
    "BattleConditionsDeleteScheduleButton",
    "BattleConditionsDeleteScheduleSelect",
    "BattleConditionsTogglePauseScheduleButton",
    "BattleConditionsTogglePauseSelect",
]
