# Generated by Django 5.1.4 on 2025-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0016_alter_susperson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsusperson',
            name='shun',
            field=models.BooleanField(default=False, help_text="Are they shunned from the Discord? If checked, user won't appear in leaderboards or earn tourney roles."),
        ),
        migrations.AddField(
            model_name='susperson',
            name='shun',
            field=models.BooleanField(default=False, help_text="Are they shunned from the Discord? If checked, user won't appear in leaderboards or earn tourney roles."),
        ),
        migrations.AlterField(
            model_name='historicalsusperson',
            name='sus',
            field=models.BooleanField(default=True, help_text='Is the person sus? If checked, they will be removed from the results on the public website.'),
        ),
        migrations.AlterField(
            model_name='susperson',
            name='sus',
            field=models.BooleanField(default=True, help_text='Is the person sus? If checked, they will be removed from the results on the public website.'),
        ),
    ]
