# Generated by Django 5.1.4 on 2025-02-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0017_historicalsusperson_shunned_susperson_shunned_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviewed',
        ),
    ]
